---
language: php

sudo: false

php:
  - 7.3

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
  slack:
    secure: QDE52Y7qq+PEEy6xagZ/eIJ2pd/BCCq0quN41pl+iwKXO72dlNlLINuro0Mis/dNlzMrmdwKLDBsl+r0Kkqq6L7TpnnpziVX88fBvMl4PXxkfJJwSV0fiBcXBz1hJi9E/n22gOVvO1orUBMSVTx5IDzVAEssnzABrPshoReEejw=

install: composer install --no-interaction

before_script:
  - mkdir -p build/logs
  - php -S localhost:9000 -t tests >/dev/null 2>&1 &

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
